# This is a basic workflow to help you get started with Actions

name: on-acr-image-push

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [on-acr-image-push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-image-to-acr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - env:
         EVENT_TYPE: ${{ github.event.event_type }}
         ENV: ${{ github.event.client_payload.env }}
         IMAGE: ${{ github.event.client_payload.image }}
        run: |
          echo $EVENT_TYPE
          echo $ENV
          echo $IMAGE
