# This is a basic workflow to help you get started with Actions

name: on-acr-image-push

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [on-acr-image-push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
      - run: 'echo "trigger: ${{ github.event.event_type }}"'
      - run: 'echo "  image: ${{ github.event.client_payload.image }}"'
      - run: 'echo "    env: ${{ github.event.client_payload.env }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
