name: acr_image_push
# This workflow is triggered on new acr image push
on:
  repository_dispatch:
    types: [acr_image_push]

jobs:
  build:
    name:  acr_image_push
    runs-on: ubuntu-latest
    steps:
      # Add you custom logic below this line - example below
      - name: Print event type
        run: echo 'event_type:${{ github.event.event_type }} name:${{ github.event_name }}' # Will be 'acr_image_push'
      - name: Print ACR Image Push details
        run: echo 'id:${{ github.event.client_payload.acr_image_push.id }} type:${{ github.event.client_payload.acr_image_push.action }}'
