on:
  workflow_dispatch:
    inputs:
      action:
        description: 'the acr action'
        required: true
jobs:
  myEvent:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}    
    steps:
       - name: Dump GitHub context
       - run: |
           echo '${{ toJSON(github) }}'
           echo 'ACR Webhook Recieved: [ acr::action::push ] '
