on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Consume ACR Webhook Action'
        required: true
jobs:
  myEvent:
    runs-on: ubuntu-latest 
    steps:
       - run: |
           echo '${{ toJSON(github) }}'
           echo 'ACR Webhook Recieved: [ acr::action::push ] '
