on:
  workflow_dispatch:
    inputs:
      action:
        description: 'the acr action'
        required: true
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
         with:
           client-payload: ${{ toJson(github) }}
       - run: echo ${{ github.event.client_payload }}

        
